name: Build on Pull Request

on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

# run build
      - name: Build
        run: ./gradlew build

# prepare ui test
      - name: Install Playwright E2E Browsers
        run: npx playwright install --with-deps

# run ui tests
      - name: E2E
        run: ./gradlew npm_run_e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
